apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitops-demo
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: gitops-demo
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
